# -*- coding: utf-8 -*-

from scrapy import Field


class TnaWebsiteItem(Field):
    ID = Field()
    TITLE = Field()
    CONTENT = Field()
    DESCRIPTION = Field()
    DATE_MODIFIED = Field()
    DATE_CREATED = Field()
    COVERING_DATES = Field()
    SOURCE = Field()
    SUBJECTS = Field()
    KEYWORDS = Field()
    SCHEMA = Field()
    # define the fields for your item here like:
    # name = scrapy.Field()
    pass


starturls = ['https://www.nationalarchives.gov.uk/films/']

denyurls = ['/atoz/',
            '/webarchive.nationalarchives.gov.uk/',
            '/discovery.nationalarchives.gov.uk/',
            '/media.nationalarchives.gov.uk/',
            '/blog.nationalarchives.gov.uk/',
            '/bookshop.nationalarchives.gov.uk/',
            '/images.nationalarchives.gov.uk/',
            '/academic',
            '/accessions/accprograms/',
            '/assetbank-nationalarchives/',
            '/advanceorders',
            '/advanceorders/includes/',
            '/advanceorders/js/',
            '/archives/',
            '/archon/',
            '/bookshop/',
            '/bookshop/account.aspx',
            '/bookshop/App_Code/',
            '/bookshop/basket.aspx',
            '/bookshop/Bin/',
            '/bookshop/Controls/',
            '/bookshop/coupn.aspx',
            '/bookshop/digital_receipt.aspx',
            '/bookshop/ordercomplete.aspx',
            '/bookshop/process_order.aspx',
            '/bookshop/receiptfailure.aspx',
            '/bookshop/searchresult.aspx',
            '/bookshop/titleshow.asp',
            '/bookshop/xml/',
            '/browse-guidance-standards/',
            '/Bridging',
            '/business',
            '/cab/',
            '/cabinetpapers',
            '/cabinetpaperssearch',
            '/catalogue',
            '/celebratingcensus',
            '/census',
            '/chat',
            '/clickandbuy',
            '/conferences/ ',
            '/conferencesclosed',
            '/contact/form/',
            '/cover-it-live/',
            '/css',
            '/currency',
            '/customerrors/',
            '/dc-framework/',
            '/dc-guidance/',
            '/dc-riskassessment/',
            '/dc-service/',
            '/dc-training/',
            '/digexpress',
            '/digitalcontinuity',
            '/digitalexpress/',
            '/discovery',
            '/document_handling',
            '/documentsonline',
            '/documentphotos/',
            '/documents/mog.pdf',
            '/documents/old/',
            '/documents/',
            '/dol',
            '/Download.aspx',
            '/droid/',
            '/e179/includes/',
            '/e179/scripts/',
            '/ecards',
            '/educationservice',
            '/edwardii-conference',
            '/emergency.htm',
            '/enewsletter',
            '/enewsletter/global/',
            '/enewsletter/includes/',
            '/equity',
            '/equity/includes/',
            '/equity/scripts/',
            '/ERO/*',
            '/eventsbooking',
            '/eventsbooking/email_templates/',
            '/eventsbooking/includes/',
            '/eventsbooking/scripts/',
            '/failover',
            '/Filestore/',
            '/filmindex.htm',
            '/foi/pubscheme/',
            '/gazettestender',
            '/gettingstarted',
            '/gwdb',
            '/help/',
            '/ia/',
            '/imagelibrary',
            '/help-with-your-research/',
            '/hospitalrecords/includes/',
            '/househistory',
            '/ichora5',
            '/images/',
            '/information-principles',
            '/includes/',
            '/irlist/includes/',
            '/labs-maintenance.htm',
            '/legion',
            '/livingin1901',
            '/livingthepoorlife',
            '/localhistory',
            '/media',
            '/militaryhistory',
            '/museum',
            '/museum/includes/',
            '/mypage',
            '/news/999-snow.htm',
            '/online/includes',
            '/PageNotFound/',
            '/pas-198',
            '/place-of-deposit.php?',
            '/podcasts',
            '/poor_law',
            '/popup/',
            '/portal',
            '/preservation',
            '/presspreview/',
            '/pronom',
            '/pronom/product/',
            '/pronom/vendor/',
            '/recordpreviews/',
            '/recordsmanagement',
            '/records/',
            '/registration',
            '/registration/includes/',
            '/registration/js/',
            '/religiousarchives',
            '/research-guides/',
            '/results.php?',
            '/rss'
            '/script/',
            '/search/',
            '/Search/',
            '/search/name_search.aspx',
            '/searchthearchives',
            '/sepia/images',
            '/SFACS',
            '/spanish-civil-war',
            '/streamline',
            '/swf',
            '/TNACRL',
            '/towton',
            '/transfer',
            '/video',
            '/wdytya',
            'wrong*',
            '/xml',
            '/yourarchives',
            '/zoomify',
            'zoomifyImagePath',
            '/zzz/']

allowurls = ['/films/']
