from scrapy import Field


class TnaWebsiteItem(Field):
    ID = Field()
    TITLE = Field()
    CONTENT = Field()
    DESCRIPTION = Field()
    START_DATE = Field()
    END_DATE = Field()
    DATE_MODIFIED = Field()
    DATE_CREATED = Field()
    SOURCE = Field()
    SUBJECTS = Field()
    KEYWORDS = Field()
    SCHEMA = Field()
    PLACE_NAME = Field()
    PLACE_COUNTRY = Field()
    CATALOGUE_REFERENCE = Field()
    pass


starturls = ['http://www.nationalarchives.gov.uk/pathways/blackhistory/',
             'http://www.nationalarchives.gov.uk/pathways/citizenship/',
             'http://www.nationalarchives.gov.uk/pathways/census/',
             'https://www.nationalarchives.gov.uk/pathways/firstworldwar/']

denyurls = ['/atoz/',
            '/webarchive.nationalarchives.gov.uk/',
            '/discovery.nationalarchives.gov.uk/',
            '/media.nationalarchives.gov.uk/',
            '/blog.nationalarchives.gov.uk/',
            '/bookshop.nationalarchives.gov.uk/',
            '/images.nationalarchives.gov.uk/',
            '/academic',
            '/accessions/accprograms/',
            '/additional_image_types.asp?',
            '/assetbank-nationalarchives/',
            '/advanceorders',
            '/advanceorders/includes/',
            '/advanceorders/js/',
            '/archives/',
            '/archon/',
            '/bookshop/',
            '/bookshop/account.aspx',
            '/bookshop/App_Code/',
            '/bookshop/basket.aspx',
            '/bookshop/Bin/',
            '/bookshop/Controls/',
            '/bookshop/coupn.aspx',
            '/bookshop/digital_receipt.aspx',
            '/bookshop/ordercomplete.aspx',
            '/bookshop/process_order.aspx',
            '/bookshop/receiptfailure.aspx',
            '/bookshop/searchresult.aspx',
            '/bookshop/titleshow.asp',
            '/bookshop/xml/',
            '/browse-guidance-standards/',
            '/Bridging',
            '/business',
            '/cab/',
            '/cabinetpapers',
            '/cabinetpaperssearch',
            '/catalogue',
            '/celebratingcensus',
            '/chat',
            '/clickandbuy',
            '/conferences/ ',
            '/conferencesclosed',
            '/contact/form/',
            '/cover-it-live/',
            '/credits/',
            '/css',
            '/currency',
            '/customerrors/',
            '/dates.asp?',
            '/dc-framework/',
            '/dc-guidance/',
            '/dc-riskassessment/',
            '/dc-service/',
            '/dc-training/',
            '/digexpress',
            '/digitalcontinuity',
            '/digitalexpress/',
            '/discovery',
            '/document_handling',
            '/documentsonline',
            '/documentphotos/',
            '/documents/mog.pdf',
            '/documents/old/',
            '/documents/',
            '/dol',
            '/Download.aspx',
            '/droid/',
            '/e179/includes/',
            '/e179/scripts/',
            '/ecards',
            '/educationservice',
            '/edwardii-conference',
            '/emergency.htm',
            '/enewsletter',
            '/enewsletter/global/',
            '/enewsletter/includes/',
            '/equity',
            '/equity/includes/',
            '/equity/scripts/',
            '/ERO/*',
            '/eventsbooking',
            '/eventsbooking/email_templates/',
            '/eventsbooking/includes/',
            '/eventsbooking/scripts/',
            '/failover',
            '/Filestore/',
            '/filmindex.htm',
            '/focuson/',
            '/foi/pubscheme/',
            '/gazettestender',
            '/gettingstarted',
            '/gwdb',
            '/help/',
            '/ia/',
            '/image.htm',
            '/image_lg.htm?',
            '/imagelibrary',
            '/help-with-your-research/',
            '/hospitalrecords/includes/',
            '/househistory',
            '/ichora5',
            '/images/',
            '/information-principles',
            '/includes/',
            '/irlist/includes/',
            '/itemenlarge.asp?',
            '/itemzoom.asp?',
            '/labs-maintenance.htm',
            '/legion',
            '/livingin1901',
            '/livingthepoorlife',
            '/localhistory',
            '/maps/',
            '/media',
            '/militaryhistory',
            '/museum/includes/',
            '/mypage',
            '/news/999-snow.htm',
            '/objectlist.asp?',
            '/online/includes',
            '/PageNotFound/',
            '/pas-198',
            '/place-of-deposit.php?',
            '/podcasts',
            '/poor_law',
            '/popup/',
            '/popups/',
            '/portal',
            '/preservation',
            '/presspreview/',
            '/pronom',
            '/pronom/product/',
            '/pronom/vendor/',
            '/proprietor.asp?',
            '/quiz/',
            '/recordpreviews/',
            '/recordsmanagement',
            '/records/',
            '/regenlarge.asp?',
            '/registration',
            '/registration/includes/',
            '/registration/js/',
            '/regzoom.asp?',
            '/religiousarchives',
            '/research-guides/',
            '/results.php?',
            '/rss'
            '/script/',
            '/search/',
            '/Search/',
            '/search/name_search.aspx',
            '/searchthearchives',
            '/sepia/images',
            '/SFACS',
            '/spanish-civil-war',
            '/streamline',
            '/swf',
            '/themes.asp?',
            '/timelines/',
            '/TNACRL',
            '/towton',
            '/transfer',
            '/video',
            '/wdytya',
            'wrong*',
            '/xml',
            '/yourarchives',
            '/zoomify',
            'zoomifyImagePath',
            '/zzz/']

allowurls = ['/citizenship/', '/census/', '/blackhistory/', '/firstworldwar/']
